kind: Namespace
apiVersion: v1
metadata:
  name: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-demo-deployment
  namespace: ${namespace}
spec:
  selector:
    matchLabels:
      app: ruby-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: ruby-demo
    spec:
      containers:
        - name: ruby-demo
          # enter the path to your image, be sure to include the correct region prefix
          image: ${region}/${name}/${image}:${hash}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ruby-demo-service
  namespace: ${namespace}
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ruby-demo